version: "3.9"

services:
  django-app:
    image: "django-image"
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - 9000:9000
    command: sh -c "python manage.py runserver 0.0.0.0:9000"