version: "3.9"

services:
  django-app:
    image: "django-image"
    build:
      context: .
    volumes:
      - ./app:/app
      - static-data-volume:/vol/web
    ports:
      - 9000:9000
    command: sh -c "
        python manage.py checkdb &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:9000"
    environment:
      - DB_HOST=db
      - DB_USER=dev
      - DB_NAME=recipedb
      - DB_PASS=postgres
    depends_on:
      - db
  
  db:
    image: postgres:15.7-alpine3.20
    volumes:
      - dev-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recipedb

volumes:
  dev-db:
  static-data-volume: