name: workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: docker-compose run --rm django-app sh -c "python manage.py test"

  